- pom.xml
- src/main/java/id/co/metrodata/serverApp/controllers/EmployeeController.java
- src/main/java/id/co/metrodata/serverApp/controllers/UserController.java
- src/main/java/id/co/metrodata/serverApp/models/Employee.java
- src/main/java/id/co/metrodata/serverApp/models/User.java
- src/main/java/id/co/metrodata/serverApp/models/dto/UserRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/EmployeeRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/UserRepository.java
- src/main/java/id/co/metrodata/serverApp/services/EmployeeService.java
- src/main/java/id/co/metrodata/serverApp/services/UserService.java
- src/main/java/id/co/metrodata/serverApp/utils/ModelMapperUtil.java
- src/main/resources/application.properties
- src/test/java/id/co/metrodata/serverApp/ServerAppApplicationTests.java
> Add CRUD_User-Employee

- src/main/java/id/co/metrodata/serverApp/controllers/PrivilegeController.java
- src/main/java/id/co/metrodata/serverApp/controllers/RoleController.java
- src/main/java/id/co/metrodata/serverApp/models/Privilege.java
- src/main/java/id/co/metrodata/serverApp/models/Role.java
- src/main/java/id/co/metrodata/serverApp/repositories/PrivilegeRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/RoleRepository.java
- src/main/java/id/co/metrodata/serverApp/services/PrivilegeService.java
- src/main/java/id/co/metrodata/serverApp/services/RoleService.java
- src/main/resources/application.properties
privilege dan role_privilege input manual di database
> Crud role privilege

- src/main/java/id/co/metrodata/serverApp/controllers/ClassroomController.java
- src/main/java/id/co/metrodata/serverApp/models/Classroom.java
- src/main/java/id/co/metrodata/serverApp/repositories/ClassroomRepository.java
- src/main/java/id/co/metrodata/serverApp/services/ClassroomService.java
Note : nama model class diganti jadi classroom, dan endpoint menjadi "/classroom"
> Crud class

- src/main/java/id/co/metrodata/serverApp/controllers/GradeController.java
- src/main/java/id/co/metrodata/serverApp/models/Grade.java
- src/main/java/id/co/metrodata/serverApp/repositories/GradeRepository.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
> Add CRUD Grade

- src/main/java/id/co/metrodata/serverApp/controllers/TaskController.java
- src/main/java/id/co/metrodata/serverApp/models/Task.java
- src/main/java/id/co/metrodata/serverApp/repositories/TaskRepository.java
- src/main/java/id/co/metrodata/serverApp/services/TaskService.java
> Add CRUD Task

- src/main/java/id/co/metrodata/serverApp/controllers/CommentController.java
- src/main/java/id/co/metrodata/serverApp/controllers/DiscussionController.java
- src/main/java/id/co/metrodata/serverApp/models/Comment.java
- src/main/java/id/co/metrodata/serverApp/models/Discussion.java
- src/main/java/id/co/metrodata/serverApp/models/dto/CommentRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/CommentRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/DiscussionRepository.java
- src/main/java/id/co/metrodata/serverApp/services/CommentService.java
- src/main/java/id/co/metrodata/serverApp/services/DiscussionService.java
> Crud discussion comment

- src/main/java/id/co/metrodata/serverApp/controllers/GradeController.java
- src/main/java/id/co/metrodata/serverApp/controllers/MateriController.java
- src/main/java/id/co/metrodata/serverApp/controllers/SegmentController.java
- src/main/java/id/co/metrodata/serverApp/controllers/TaskController.java
- src/main/java/id/co/metrodata/serverApp/controllers/TopicController.java
- src/main/java/id/co/metrodata/serverApp/controllers/UserController.java
- src/main/java/id/co/metrodata/serverApp/models/Employee.java
- src/main/java/id/co/metrodata/serverApp/models/Segment.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/MateriRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/SegmentRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/UserRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/SegmentRepository.java
- src/main/java/id/co/metrodata/serverApp/services/ClassroomService.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
- src/main/java/id/co/metrodata/serverApp/services/MateriService.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentService.java
- src/main/java/id/co/metrodata/serverApp/services/TaskService.java
- src/main/java/id/co/metrodata/serverApp/services/TopicService.java
- src/main/java/id/co/metrodata/serverApp/services/UserService.java
> Feat class

- src/main/java/id/co/metrodata/serverApp/controllers/DiscussionController.java
- src/main/java/id/co/metrodata/serverApp/models/Comment.java
- src/main/java/id/co/metrodata/serverApp/models/Discussion.java
- src/main/java/id/co/metrodata/serverApp/models/Employee.java
- src/main/java/id/co/metrodata/serverApp/models/Materi.java
- src/main/java/id/co/metrodata/serverApp/models/dto/CommentRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/DiscussionRequest.java
- src/main/java/id/co/metrodata/serverApp/services/CommentService.java
- src/main/java/id/co/metrodata/serverApp/services/DiscussionService.java
- src/main/resources/application.properties
add relation with change employee because conflict
> Feat discussion

- src/main/java/id/co/metrodata/serverApp/controllers/CommentController.java
- src/main/java/id/co/metrodata/serverApp/controllers/DiscussionController.java
- src/main/java/id/co/metrodata/serverApp/controllers/GradeController.java
- src/main/java/id/co/metrodata/serverApp/models/Employee.java
- src/main/java/id/co/metrodata/serverApp/models/Grade.java
- src/main/java/id/co/metrodata/serverApp/models/Segment.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/CommentRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/DiscussionRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/GradeRequest.java
- src/main/java/id/co/metrodata/serverApp/services/CommentService.java
- src/main/java/id/co/metrodata/serverApp/services/DiscussionService.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
relation with segment and employee
> feat grade: add relation

- src/main/java/id/co/metrodata/serverApp/controllers/TopicController.java
- src/main/java/id/co/metrodata/serverApp/models/Program.java
- src/main/java/id/co/metrodata/serverApp/models/Topic.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/TopicRequest.java
- src/main/java/id/co/metrodata/serverApp/services/TopicService.java
- src/main/resources/application.properties
> feat topic: add relation program

- src/main/java/id/co/metrodata/serverApp/controllers/SegmentController.java
- src/main/java/id/co/metrodata/serverApp/models/Materi.java
- src/main/java/id/co/metrodata/serverApp/models/Segment.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentService.java
relation many to many with add table segment_materi
> Feat Segment: add relation with materi

- src/main/java/id/co/metrodata/serverApp/models/Employee.java
- src/main/java/id/co/metrodata/serverApp/models/Evaluation.java
- src/main/java/id/co/metrodata/serverApp/models/Grade.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/EvaluationRequest.java
- src/main/java/id/co/metrodata/serverApp/services/EvaluationService.java
> Feat Evaluation: change relation

- src/main/java/id/co/metrodata/serverApp/configs/AppSecurityConfig.java
- src/main/java/id/co/metrodata/serverApp/controllers/AuthController.java
- src/main/java/id/co/metrodata/serverApp/models/Employee.java
- src/main/java/id/co/metrodata/serverApp/models/Grade.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/GradeRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/LoginRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/response/LoginResponse.java
- src/main/java/id/co/metrodata/serverApp/repositories/ClassroomRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/GradeRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/ProgramRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/SegmentMateriRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/SegmentRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/TopicRepository.java
- src/main/java/id/co/metrodata/serverApp/services/AuthService.java
- src/main/java/id/co/metrodata/serverApp/services/ClassroomService.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
- src/main/java/id/co/metrodata/serverApp/services/ProgramService.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentMateriService.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentService.java
- src/main/java/id/co/metrodata/serverApp/services/TopicService.java
add feature login and add validation in topic, program, and classrom
> Feat Login and add validation

- src/main/java/id/co/metrodata/serverApp/models/Employee.java
- src/main/java/id/co/metrodata/serverApp/models/Evaluation.java
- src/main/java/id/co/metrodata/serverApp/models/Submission.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/GradeRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/ClassroomRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/EvaluationRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/GradeRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/SegmentMateriRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/SubmissionRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/TopicRepository.java
- src/main/java/id/co/metrodata/serverApp/services/ClassroomService.java
- src/main/java/id/co/metrodata/serverApp/services/EvaluationService.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentMateriService.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentService.java
- src/main/java/id/co/metrodata/serverApp/services/SubmissionService.java
- src/main/java/id/co/metrodata/serverApp/services/TopicService.java
testing grading and task but not using authority yet and fix validation for classroom, topic, segment, segmentMateri, submission, and grade
> Testing: task and grading

- src/main/java/id/co/metrodata/serverApp/controllers/MateriController.java
- src/main/java/id/co/metrodata/serverApp/models/Employee.java
- src/main/java/id/co/metrodata/serverApp/models/Evaluation.java
- src/main/java/id/co/metrodata/serverApp/models/Grade.java
- src/main/java/id/co/metrodata/serverApp/models/Materi.java
- src/main/java/id/co/metrodata/serverApp/models/Segment.java
- src/main/java/id/co/metrodata/serverApp/models/Submission.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/MateriRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/SubmissionRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/MateriRepository.java
- src/main/java/id/co/metrodata/serverApp/services/MateriService.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentService.java
- antmatcher api get program and class method.get
- repo materi -> getMateriByTopic
- add attribut submission_url
> Refactor_Materi_Submission

- pom.xml
- src/main/java/id/co/metrodata/serverApp/controllers/EmailController.java
- src/main/java/id/co/metrodata/serverApp/controllers/GradeController.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/EmailRequest.java
- src/main/java/id/co/metrodata/serverApp/services/AuthService.java
- src/main/java/id/co/metrodata/serverApp/services/EmailService.java
- src/main/java/id/co/metrodata/serverApp/services/EvaluationService.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
- src/main/java/id/co/metrodata/serverApp/services/ThymeleafService.java
- src/main/resources/application.properties
in grade refactor isEnabled user to false and send email, in register user send email
> Refactor:Grade with email, Feat:User register email

- .gitignore
- src/main/resources/templates/mail-grade.html
- src/main/resources/templates/mail-register.html
> Feat Resources

- src/main/java/id/co/metrodata/serverApp/controllers/ClassroomController.java
- src/main/java/id/co/metrodata/serverApp/controllers/SegmentController.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/EmailRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/response/LoginResponse.java
- src/main/java/id/co/metrodata/serverApp/repositories/ClassroomRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/SegmentRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/UserRepository.java
- src/main/java/id/co/metrodata/serverApp/services/AppUserDetailService.java
- src/main/java/id/co/metrodata/serverApp/services/AuthService.java
- src/main/java/id/co/metrodata/serverApp/services/ClassroomService.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentService.java
- src/main/java/id/co/metrodata/serverApp/services/UserService.java
add session id user di dalem api,
- [ Segment ] getByTrainerId
- [ Segment ] getByClassIdTrainerId
- [ Classroom ] getByTrainee
> Refactor auth

- src/main/java/id/co/metrodata/serverApp/repositories/PrivilegeRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/RoleRepository.java
- src/main/java/id/co/metrodata/serverApp/services/ClassroomService.java
- src/main/java/id/co/metrodata/serverApp/services/EmployeeService.java
- src/main/java/id/co/metrodata/serverApp/services/EvaluationService.java
- src/main/java/id/co/metrodata/serverApp/services/PrivilegeService.java
- src/main/java/id/co/metrodata/serverApp/services/ProgramService.java
- src/main/java/id/co/metrodata/serverApp/services/RoleService.java
- src/main/java/id/co/metrodata/serverApp/services/SubmissionService.java
- src/main/java/id/co/metrodata/serverApp/services/TopicService.java
- src/main/resources/application.properties
refactor validation in some service
> Validation

- src/main/java/id/co/metrodata/serverApp/controllers/EvaluationController.java
- src/main/java/id/co/metrodata/serverApp/repositories/EvaluationRepository.java
- src/main/java/id/co/metrodata/serverApp/services/EvaluationService.java
- src/main/resources/application.properties
Add evalutaion find by submission task id
> Fix submission

- src/main/java/id/co/metrodata/serverApp/controllers/TaskController.java
- src/main/java/id/co/metrodata/serverApp/repositories/TaskRepository.java
- src/main/java/id/co/metrodata/serverApp/services/TaskService.java
add enpoint for get by trainer and trainee
> Refactor: task get by user

- src/main/java/id/co/metrodata/serverApp/controllers/GradeController.java
- src/main/java/id/co/metrodata/serverApp/models/Submission.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/SubmissionRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/GradeRepository.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
- src/main/java/id/co/metrodata/serverApp/services/SubmissionService.java
- src/main/resources/application.properties
add endpoint grade by segment and submission user  not request traineeId
> grade and submission

- src/main/java/id/co/metrodata/serverApp/configs/AppSecurityConfig.java
- src/main/java/id/co/metrodata/serverApp/controllers/GradeController.java
- src/main/java/id/co/metrodata/serverApp/repositories/GradeRepository.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
- src/main/java/id/co/metrodata/serverApp/utils/ScheduledTasks.java
- Scheduler bakal di jalankan saat segment.end_date h-1 dari tanggal sekarang
> Feat Scheduler

- src/main/java/id/co/metrodata/serverApp/controllers/CategoryController.java
- src/main/java/id/co/metrodata/serverApp/controllers/ClassroomController.java
- src/main/java/id/co/metrodata/serverApp/controllers/GradeController.java
- src/main/java/id/co/metrodata/serverApp/models/Category.java
- src/main/java/id/co/metrodata/serverApp/models/Classroom.java
- src/main/java/id/co/metrodata/serverApp/models/Segment.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/ClassroomRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/EvaluationRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/SegmentRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/CategoryRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/ClassroomRepository.java
- src/main/java/id/co/metrodata/serverApp/repositories/GradeRepository.java
- src/main/java/id/co/metrodata/serverApp/services/CategoryService.java
- src/main/java/id/co/metrodata/serverApp/services/ClassroomService.java
- src/main/java/id/co/metrodata/serverApp/services/EvaluationService.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
- src/main/java/id/co/metrodata/serverApp/services/SegmentService.java
add new entity category with relation onetomany to segment and change classroom add isStatus, evaluation add session, and grade add findByClassroom
> Feat evaluation

- src/main/java/id/co/metrodata/serverApp/controllers/MateriController.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/MateriRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/MateriRepository.java
- src/main/java/id/co/metrodata/serverApp/services/GradeService.java
- src/main/java/id/co/metrodata/serverApp/services/MateriService.java
- create materi sudah get dari id trainer
- nambah api baru untuk materi getByTrainer
> Refactor Materi

- src/main/java/id/co/metrodata/serverApp/controllers/ClassroomController.java
- src/main/java/id/co/metrodata/serverApp/controllers/UserController.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/ChangeRoleRequest.java
- src/main/java/id/co/metrodata/serverApp/models/dto/request/ChangeStatusRequest.java
- src/main/java/id/co/metrodata/serverApp/repositories/ClassroomRepository.java
- src/main/java/id/co/metrodata/serverApp/services/ClassroomService.java
- src/main/java/id/co/metrodata/serverApp/services/UserService.java
ad endpoint change role, status and get class active for trainer
> Feat: endpoint change role, status, class active
